
provider:
  access_key_id: "AKIA6CPYEK2T6MULRZH5"
  secret_access_key: "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"
  region: "us-west-2"

voice_engine:
  # voice_id: "Matthew"
  # voice_id: "Joanna"
  voice_id: "Tatyana"
  # engine: "neural"
  # speech_style: "news"
  speech_style: "conversational"

  language_code: "ru-RU"

