provider:
  # https://docs.aws.amazon.com/polly/latest/dg/setting-up.html
  region: "us-west-2"

voice_engine:
  # see https://docs.aws.amazon.com/polly/latest/dg/voicelist.html
  voice_id: "Joanna"
  # voice_id: "Matthew"

  # See https://docs.aws.amazon.com/polly/latest/dg/NTTS-main.html
  engine: "neural"

  # See https://docs.aws.amazon.com/polly/latest/dg/ntts-speakingstyles.html
  speech_style: "conversational"